name: Maestro E2E Tests (Chromium)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install app dependencies
        run: npm ci

      # Step 4: Start the web server
      - name: Start web server
        run: |
          nohup npm start &
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 >/dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 1
          done

      # Step 5: Install system tools (if not already available)
      - name: Ensure system tools
        run: sudo apt-get update && sudo apt-get install -y curl bash

      # Step 6: Install Maestro
      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      # Step 7: Run Maestro Tests in Chromium
      - name: Run Maestro Tests
        run: maestro test maestro/login_test.yaml --device "chromium"
        env:
          PATH: $HOME/.maestro/bin:$PATH
