name: Maestro E2E Tests (Chromium)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install app dependencies
      - name: Install app dependencies
        run: npm ci

      # Step 4: Start web server
      - name: Start web server
        run: |
          nohup npm start &
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 >/dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 1
          done

      # Step 5: Install Maestro and run tests (Chromium)
      - name: Install Maestro and Run Tests
        run: |
          # Ensure system tools exist
          sudo apt-get update
          sudo apt-get install -y curl bash

          # Install Maestro
          curl -Ls "https://get.maestro.mobile.dev" | bash

          # Add Maestro to PATH for this shell
          export PATH=$HOME/.maestro/bin:$PATH

          # Run tests on Chromium
          maestro test maestro/login_test.yaml --device "chromium"
