name: Maestro E2E Tests (Browser)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install app dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Start the web server
      - name: Start web server
        run: |
          nohup npm start &
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 >/dev/null; then
              echo "Server up"
              break
            fi
            sleep 1
          done

      # Step 5: Install Chromium (via Playwright)
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 6: Run Maestro tests (on browser)
      - name: Run Maestro Tests
        run: maestro test maestro/login_test.yaml --device "chromium" 
        env:
          PATH: $HOME/.maestro/bin:$PATH
