name: Maestro E2E Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install app dependencies
      - name: Install app deps
        run: npm ci || npm install

      # Step 4: Start the web server
      - name: Start web server
        run: |
          nohup npm start &
          # Wait for the server to be ready
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 >/dev/null; then
              echo "Server up"
              break
            fi
            sleep 1
          done

      # Step 5: Install Maestro
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
        env:
          PATH: $HOME/.maestro/bin:$PATH

      # Step 6: Start Android Emulator
      - name: Start Android Emulator
        run: |
          echo "Starting Android emulator..."

          # Install required dependencies
          sudo apt update
          sudo apt install -y qemu-kvm libvirt-daemon libvirt-clients bridge-utils

          # Download command line tools
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -o commandlinetools.zip
          unzip commandlinetools.zip
          
          # Create the SDK folder if it doesn't exist
          mkdir -p $HOME/.android/cmdline-tools

          # Move the downloaded cmdline-tools to the right location
          mv cmdline-tools $HOME/.android/cmdline-tools/latest

          # Set ANDROID_SDK_ROOT environment variable
          echo "Setting ANDROID_SDK_ROOT"
          export ANDROID_SDK_ROOT=$HOME/.android
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

          # Accept SDK licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Install required SDK components
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"

          # Create and start the AVD (Android Virtual Device)
          echo "Creating Android AVD if not exists..."
          echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test-emulator -k "system-images;android-30;google_apis;x86_64" --force
          
          # Start the emulator
          nohup $ANDROID_SDK_ROOT/emulator/emulator -avd test-emulator -no-window -gpu off &
          
          # Wait for the emulator to be ready
          for i in {1..30}; do
            if adb devices | grep -q "emulator"; then
              echo "Emulator is ready"
              break
            fi
            sleep 5
          done

      # Step 7: Run Maestro Tests
      - name: Run Maestro Tests
        run: |
          maestro test maestro/login_test.yaml
        env:
          PATH: $HOME/.maestro/bin:$PATH
