name: E2E (Maestro)

on:
  push:
  pull_request:

jobs:
  web-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install app deps
        run: npm ci || npm install

      - name: Start web server
        run: |
          nohup npm start &
          # Wait for server to be ready
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 >/dev/null; then echo "Server up"; break; fi
            sleep 1
          done

     #Step 2: Install Maestro 
      - name: Install Maestro
        run: |
         curl -Ls "https://get.maestro.mobile.dev" | bash

      # Step 3: Start Android Emulator
      - name: Start Android Emulator
        run: |
          echo "Starting Android emulator..."
          
          # Install required dependencies
          sudo apt update
          sudo apt install -y qemu-kvm libvirt-daemon libvirt-clients bridge-utils

          # Download command line tools
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -o commandlinetools.zip
          unzip commandlinetools.zip
          
          # Create the SDK folder if it doesn't exist
          mkdir -p $HOME/.android/cmdline-tools

          # Move the downloaded cmdline-tools to the right location
          mv cmdline-tools $HOME/.android/cmdline-tools/latest

          # Accept SDK licenses
          yes | $HOME/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.android --licenses
          
          # Install required SDK components
          $HOME/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.android "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"

          # Create and start the AVD (Android Virtual Device)
          echo "Creating Android AVD if not exists..."
          echo "no" | $HOME/.android/cmdline-tools/latest/bin/avdmanager create avd -n test-emulator -k "system-images;android-30;google_apis;x86_64" --force --sdk_root=$HOME/.android
          
          # Start the emulator
          nohup $HOME/.android/emulator/emulator -avd test-emulator -no-window -gpu off &
          
          # Wait for the emulator to be ready
          for i in {1..30}; do
            if adb devices | grep -q "emulator"; then
              echo "Emulator is ready"
              break
            fi
            sleep 5
          done

      # Step 6: Run Maestro Tests
      - name: Run Maestro Tests
        run: |
          maestro test maestro/login_test.yaml
